AllCops:
  Exclude:
    - bundle/**/*
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 82

Metrics/BlockLength:
  Max: 145

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 175

Metrics/MethodLength:
  Max: 65

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 23

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/VariableNumber:
  Enabled: false
