AllCops:
  Exclude:
    - bundle/**/*
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 145

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 225

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 175

Metrics/MethodLength:
  Max: 55

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 22

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/VariableNumber:
  Enabled: false
