AllCops:
  Exclude:
    - bundle/**/*
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 175

# those metrics should be disabled
Metrics/AbcSize:
  Max: 92

Metrics/BlockLength:
  Max: 188

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 285

Metrics/CyclomaticComplexity:
  Max: 21

Metrics/MethodLength:
  Max: 70

Metrics/ParameterLists:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 24

# We use `dc` as a parameter in many methods
Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

